sudo: required
services:
  - docker
  - mongodb
language: go
go:
  - "1.11"
env:
  - GO111MODULE=on
script:
  # build/test
  - make static
  - make test
  # deploy, only if on master and not a PR
  - |
    if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
      then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      make build push;
    fi
