version: "3.5"

networks:
  default:
    external:
      name: gateway

services:
  pawndex:
    image: "southclaws/pawndex"
    restart: on-failure
    environment:
      PAWNDEX_BIND: "0.0.0.0:80"
      PAWNDEX_GITHUBTOKEN: "${GITHUB_TOKEN}"
      PAWNDEX_SEARCHINTERVAL: 30s
      PAWNDEX_SCRAPEINTERVAL: 30s
      PAWNDEX_DATABASEPATH: /pawndex/pawndex.db
    volumes:
      - "${DATA_DIR}/pawndex:/pawndex"
    networks:
      - default
    labels:
      traefik.enable: true
      traefik.http.routers.pawndex.rule: Host(`api.sampctl.com`)
      traefik.http.routers.pawndex.entrypoints: https
      traefik.http.routers.pawndex.tls.certresolver: default
      com.centurylinklabs.watchtower.enable: true
